networks:
  blanas:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          ip_range: 172.19.1.0/24

services:
  db:
    container_name: db
    hostname: db
    image: mariadb:11.4
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/blanas.cnf
      - ./_docker/mysql:/var/lib/mysql
      - ./setup:/home
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      TZ: ${TimeZone}
    command: >
      bash -c " chmod 644 /etc/mysql/conf.d/blanas.cnf && /usr/local/bin/docker-entrypoint.sh mariadbd "
    networks:
      blanas:
        ipv4_address: 172.19.1.1

  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    environment:
      PMA_HOST: db
      PMA_USER: root
      TZ: ${TimeZone}
    depends_on:
      - db
    networks:
      blanas:
        ipv4_address: 172.19.1.2

  proxy:
    container_name: proxy
    image: nginx:1.25
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
    environment:
      TZ: ${TimeZone}
    ports:
      - 5080:80
      - 5443:443
    networks:
      blanas:
        ipv4_address: 172.19.1.3
    depends_on:
      - blanas

  blanas:
    container_name: blanas
    hostname: blanas
    build:
      dockerfile: Dockerfile
      context: ./conf/php82
    volumes:
      - ./src:/var/www/html
      - ./_docker/nas:/var/www/private/nas
    networks:
      blanas:
        ipv4_address: 172.19.1.4
    environment:
      TZ: ${TimeZone}
    depends_on:
      - db

  coturn:
    container_name: coturn
    image: coturn/coturn
    networks:
      blanas:
        ipv4_address: 172.19.1.5
    volumes:
      - ./conf/coturn.conf:/etc/coturn/turnserver.conf
      - ./conf/cert.pem:/etc/coturn/cert.pem
      - ./conf/pkey.pem:/etc/coturn/pkey.pem
    environment:
      - TURN_REALM=${TurnServer}
      - TURN_SERVER_NAME=${TurnServer}

  signaling:
    container_name: signaling
    networks:
      blanas:
        ipv4_address: 172.19.1.6
    build:
      context: .
      dockerfile: conf/ws/Dockerfile
    #restart: unless-stopped
    ports:
      - 3001:3001
    #volumes:
    #  - ./web_socket/src:/app
    environment:
      - CGO_ENABLED=1
